/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as MyDetailsIndexRouteImport } from './routes/my-details/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CriticsIndexRouteImport } from './routes/critics/index'
import { Route as ReviewsIdRouteImport } from './routes/reviews/$id'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as CriticsIdRouteImport } from './routes/critics/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDetailsIndexRoute = MyDetailsIndexRouteImport.update({
  id: '/my-details/',
  path: '/my-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticsIndexRoute = CriticsIndexRouteImport.update({
  id: '/critics/',
  path: '/critics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticsIdRoute = CriticsIdRouteImport.update({
  id: '/critics/$id',
  path: '/critics/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/critics/$id': typeof CriticsIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/critics': typeof CriticsIndexRoute
  '/login': typeof LoginIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/my-details': typeof MyDetailsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/critics/$id': typeof CriticsIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/critics': typeof CriticsIndexRoute
  '/login': typeof LoginIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/my-details': typeof MyDetailsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/critics/$id': typeof CriticsIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/critics/': typeof CriticsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/my-details/': typeof MyDetailsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/critics/$id'
    | '/movies/$id'
    | '/reviews/$id'
    | '/critics'
    | '/login'
    | '/movies'
    | '/my-details'
    | '/register'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/critics/$id'
    | '/movies/$id'
    | '/reviews/$id'
    | '/critics'
    | '/login'
    | '/movies'
    | '/my-details'
    | '/register'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/critics/$id'
    | '/movies/$id'
    | '/reviews/$id'
    | '/critics/'
    | '/login/'
    | '/movies/'
    | '/my-details/'
    | '/register/'
    | '/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriticsIdRoute: typeof CriticsIdRoute
  MoviesIdRoute: typeof MoviesIdRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  CriticsIndexRoute: typeof CriticsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  MyDetailsIndexRoute: typeof MyDetailsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-details/': {
      id: '/my-details/'
      path: '/my-details'
      fullPath: '/my-details'
      preLoaderRoute: typeof MyDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critics/': {
      id: '/critics/'
      path: '/critics'
      fullPath: '/critics'
      preLoaderRoute: typeof CriticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critics/$id': {
      id: '/critics/$id'
      path: '/critics/$id'
      fullPath: '/critics/$id'
      preLoaderRoute: typeof CriticsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriticsIdRoute: CriticsIdRoute,
  MoviesIdRoute: MoviesIdRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  CriticsIndexRoute: CriticsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  MyDetailsIndexRoute: MyDetailsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
