/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as MyDetailsIndexRouteImport } from './routes/my-details/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CriticsIndexRouteImport } from './routes/critics/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDetailsIndexRoute = MyDetailsIndexRouteImport.update({
  id: '/my-details/',
  path: '/my-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticsIndexRoute = CriticsIndexRouteImport.update({
  id: '/critics/',
  path: '/critics/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/critics': typeof CriticsIndexRoute
  '/login': typeof LoginIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/my-details': typeof MyDetailsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/critics': typeof CriticsIndexRoute
  '/login': typeof LoginIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/my-details': typeof MyDetailsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/critics/': typeof CriticsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/my-details/': typeof MyDetailsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/critics'
    | '/login'
    | '/movies'
    | '/my-details'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/critics'
    | '/login'
    | '/movies'
    | '/my-details'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/critics/'
    | '/login/'
    | '/movies/'
    | '/my-details/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CriticsIndexRoute: typeof CriticsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  MyDetailsIndexRoute: typeof MyDetailsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-details/': {
      id: '/my-details/'
      path: '/my-details'
      fullPath: '/my-details'
      preLoaderRoute: typeof MyDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critics/': {
      id: '/critics/'
      path: '/critics'
      fullPath: '/critics'
      preLoaderRoute: typeof CriticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CriticsIndexRoute: CriticsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  MyDetailsIndexRoute: MyDetailsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
