# @Api_HostAddress = http://localhost:5000/api/
@Api_HostAddress = http://localhost:8080/api/ 
// 5000 for local development.
// 8080 for docker development.

@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMWEzYTcxZC0xM2E1LTQwOWUtOWZjZC00OGJkMDgxYzk5NzEiLCJlbWFpbCI6ImpvaG4zQHRlc3QuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImFlZDQ1OTlmLWFiZWItNGQ3Yi1hZjQ2LWZlNmQ3OTQzZWQ1YiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3MzU4MDAxMjEsImlzcyI6IkNpbmVTbGF0ZSIsImF1ZCI6IkNpbmVTbGF0ZSJ9._MjqTYLyL-9vMbL9FeT63bPytZfy5XHMCx1mTuiB6S8

### Login Success

POST {{Api_HostAddress}}users/login HTTP/1.1
content-type: application/json

{
    "email": "john@test.com",
    "password": "SuperS3cre7!"
}

### Login Fail

POST {{Api_HostAddress}}users/login HTTP/1.1
content-type: application/json

{
    "email": "123123@test.com",
    "password": "Sup3r"
}

### Register Success

POST {{Api_HostAddress}}users/register HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john@test.com",
    "password": "SuperS3cre7!"
}

### Register Fail

POST {{Api_HostAddress}}users/register HTTP/1.1
content-type: application/json

{
    "firstname": "JohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohn",
    "lastname": "Doe",
    "email": "johnm",
    "password": "badPassword"
}

### Movies List

GET {{Api_HostAddress}}movies/now_playing?page=1
content-type: application/json
Authorization: {{Token}}

### Movies Details

GET {{Api_HostAddress}}movies/912649
content-type: application/json
Authorization: {{Token}}

### Admin Test

GET {{Api_HostAddress}}admin 
content-type: application/json
Authorization: {{Token}}

### Me 

GET {{Api_HostAddress}}users/me HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Latest 

GET {{Api_HostAddress}}reviews/?page=1 HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Update 

PUT {{Api_HostAddress}}reviews/ HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Delete 

DELETE  {{Api_HostAddress}}reviews/31640b26-60b2-4fea-8058-7335954c640f HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Create 

POST   {{Api_HostAddress}}reviews/ HTTP/1.1
content-type: application/json
Authorization: {{Token}}

{
    "rating": 2,
    "movieId": 912649,
    "text": "Did not like it...",
    "containsSpoilers": false
}