# @Api_HostAddress = http://localhost:5000/api/
@Api_HostAddress = http://localhost:8080/api/ 
// 5000 for local development.
// 8080 for docker development.

@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjYyNTc3NS03YWQ2LTQwZWEtYTA2OC01MDUzMjIxYWFmNzIiLCJlbWFpbCI6ImpvaG5AdGVzdC5jb20iLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNmI1OTBmYTItOGYzMy00M2ZhLWIwM2YtMTdmNjkzZjM1NGQ3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTczNzE3OTA3NywiaXNzIjoiQ2luZVNsYXRlIiwiYXVkIjoiQ2luZVNsYXRlIn0.62toMBFcwgYsF26lip5uYgW7QvY3c76fBZCLH-Ex6po

### Login Success

POST {{Api_HostAddress}}users/login HTTP/1.1
content-type: application/json

{
    "email": "john@test.com",
    "password": "SuperS3cre7!"
}

### Login Fail

POST {{Api_HostAddress}}users/login HTTP/1.1
content-type: application/json

{
    "email": "123123@test.com",
    "password": "Sup3r"
}

### Register Success

POST {{Api_HostAddress}}users/register HTTP/1.1
content-type: application/json

{
    "username": "theJohnDoe",
    "email": "john@test.com",
    "password": "SuperS3cre7!"
}

### Register Fail

POST {{Api_HostAddress}}users/register HTTP/1.1
content-type: application/json

{
    "username": "JohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohnJohn",
    "email": "johnm",
    "password": "badPassword"
}

### Movies List

GET {{Api_HostAddress}}movies/now_playing?page=1
content-type: application/json
Authorization: {{Token}}

### Movies Details

GET {{Api_HostAddress}}movies/912649
content-type: application/json
Authorization: {{Token}}

### Admin Test

GET {{Api_HostAddress}}admin 
content-type: application/json
Authorization: {{Token}}

### Me 

GET {{Api_HostAddress}}users/me HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Latest 

GET {{Api_HostAddress}}reviews/?page=1 HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Reviews By Movie Id 

GET {{Api_HostAddress}}reviews/912649?page=1 HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Update 

PUT {{Api_HostAddress}}reviews/ HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Delete 

DELETE  {{Api_HostAddress}}reviews/31640b26-60b2-4fea-8058-7335954c640f HTTP/1.1
content-type: application/json
Authorization: {{Token}}

### Review Create 

POST   {{Api_HostAddress}}reviews/ HTTP/1.1
content-type: application/json
Authorization: {{Token}}

{
    "rating": 2,
    "movieId": 1241982,
    "text": "Did not like it...",
    "containsSpoilers": false
}