@Api_HostAddress = http://localhost:5000/api

###

POST {{Api_HostAddress}}/users/login HTTP/1.1
content-type: application/json

{
    "email": "john@test.com",
    "password": "sup3rsecre7"
}

###

POST {{Api_HostAddress}}/users/register HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john2@test.com",
    "password": "SuperS3cre7!"
}

###

POST {{Api_HostAddress}}/users/register HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john2@test.com",
    "password": "badPassword"
}

###

POST {{Api_HostAddress}}/users/register HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john2@test.com",
    "password": "SuperS3cre7!"
}