name: .NET CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - './Server/**'
  pull_request:
    paths:
      - './Server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Add solution
        working-directory: ./Server
        run: dotnet new sln

      - name: Add projects to solution
        working-directory: ./Server
        run: dotnet sln add **/**/*.csproj

      - name: Restore dependencies
        working-directory: ./Server
        run: dotnet restore

      - name: Build
        working-directory: ./Server
        run: dotnet build --no-restore --configuration Release

      - name: Test
        working-directory: ./Server
        run: |
          dotnet test --configuration Release \
            --collect "XPlat Code Coverage" \
            --results-directory "TestResults" \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=TestResults/coverage.cobertura.xml \
            /p:Threshold=70 \
            /p:ThresholdType=line \
            /p:ThresholdStat=total
            
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: LS
        working-directory: ./Server
        run: |
          ls
          cd ./TestResults
          ls

      - name: Generate coverage report
        working-directory: ./Server
        run: |
          reportgenerator \
            -reports:TestResults/coverage.cobertura.xml \
            -targetdir:TestResults/coveragereport \
            -reporttypes:TextSummary
